no change     /cvmfs/ai.mila.quebec/apps/x86_64/debian/anaconda/3/condabin/conda
no change     /cvmfs/ai.mila.quebec/apps/x86_64/debian/anaconda/3/bin/conda
no change     /cvmfs/ai.mila.quebec/apps/x86_64/debian/anaconda/3/bin/conda-env
no change     /cvmfs/ai.mila.quebec/apps/x86_64/debian/anaconda/3/bin/activate
no change     /cvmfs/ai.mila.quebec/apps/x86_64/debian/anaconda/3/bin/deactivate
no change     /cvmfs/ai.mila.quebec/apps/x86_64/debian/anaconda/3/etc/profile.d/conda.sh
no change     /cvmfs/ai.mila.quebec/apps/x86_64/debian/anaconda/3/etc/fish/conf.d/conda.fish
no change     /cvmfs/ai.mila.quebec/apps/x86_64/debian/anaconda/3/shell/condabin/Conda.psm1
no change     /cvmfs/ai.mila.quebec/apps/x86_64/debian/anaconda/3/shell/condabin/conda-hook.ps1
no change     /cvmfs/ai.mila.quebec/apps/x86_64/debian/anaconda/3/lib/python3.7/site-packages/xontrib/conda.xsh
no change     /cvmfs/ai.mila.quebec/apps/x86_64/debian/anaconda/3/etc/profile.d/conda.csh
no change     /home/mila/z/zixuan.li/.bashrc
No action taken.
Loading checkpoint shards:   0%|                                                                                                               | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|██████████████████████████████████▎                                                                    | 1/3 [00:12<00:25, 12.99s/it]Loading checkpoint shards:  67%|████████████████████████████████████████████████████████████████████▋                                  | 2/3 [00:25<00:12, 12.93s/it]Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:31<00:00,  9.71s/it]Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:31<00:00, 10.59s/it]
Some weights of the model checkpoint at /network/scratch/z/zixuan.li/experiment_ppo_model/coverage were not used when initializing GPTJForCausalLM: ['v_head.2.bias', 'v_head.2.weight', 'v_head.0.bias', 'v_head.0.weight']
- This IS expected if you are initializing GPTJForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing GPTJForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Loading checkpoint shards:   0%|                                                                                                               | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|██████████████████████████████████▎                                                                    | 1/3 [00:12<00:24, 12.30s/it]Loading checkpoint shards:  67%|████████████████████████████████████████████████████████████████████▋                                  | 2/3 [00:25<00:12, 12.75s/it]Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:30<00:00,  9.49s/it]Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:30<00:00, 10.33s/it]
Some weights of the model checkpoint at /network/scratch/z/zixuan.li/experiment_ppo_model/coverage were not used when initializing GPTJForCausalLM: ['v_head.2.bias', 'v_head.2.weight', 'v_head.0.bias', 'v_head.0.weight']
- This IS expected if you are initializing GPTJForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing GPTJForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Found cached dataset parquet (/home/mila/z/zixuan.li/.cache/huggingface/datasets/CarperAI___parquet/CarperAI--openai_summarize_tldr-536d9955f5e6f921/0.0.0/14a00e99c0d15a23649d0db8944380ac81082d4b021f398733dd84f3a6c569a7)
Found cached dataset parquet (/home/mila/z/zixuan.li/.cache/huggingface/datasets/CarperAI___parquet/CarperAI--openai_summarize_tldr-536d9955f5e6f921/0.0.0/14a00e99c0d15a23649d0db8944380ac81082d4b021f398733dd84f3a6c569a7)
  0%|                                                                                                                                       | 0/6553 [00:00<?, ?it/s]/home/mila/z/zixuan.li/.conda/envs/sum/lib/python3.10/site-packages/transformers/generation/utils.py:1219: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
  0%|                                                                                                                            | 1/6553 [00:15<27:36:42, 15.17s/it]  0%|                                                                                                                            | 2/6553 [00:21<17:56:23,  9.86s/it]  0%|                                                                                                                            | 3/6553 [00:26<14:25:03,  7.92s/it]  0%|                                                                                                                            | 4/6553 [00:37<16:23:15,  9.01s/it]  0%|                                                                                                                            | 5/6553 [00:48<17:37:27,  9.69s/it]